version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/storedb
    volumes:
      - ./images:/minio


  db:
    container_name: db
    restart: always
    ports:
      - "5000:5432"
    build:
      context: src/main/docker
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storedb

volumes:
  minio: